#!/bin/bash

# lbnebuild
# Create setup file for running.

# LBNE setup.
source $LBNE_INSDIR/lbnesetup.sh

cd $LBNE_DEVDIR/workdir
RUNSCRIPT=$LBNE_DEVDIR/run.sh
rm -f $RUNSCRIPT
echo "source $LBNE_INSDIR/lbnesetup.sh" >>$RUNSCRIPT
for SETUP in $LBNE_DEVDIR/workdir/localProducts*/setup; do
  echo source $SETUP >>$RUNSCRIPT
done
echo mrbslp >>$RUNSCRIPT

echo To set up to run with this build:
echo source $RUNSCRIPT
