#!/bin/bash

# lbnerun
# Run a command in the lbne-dev run environment.

RUNSCRIPT=$LBNE_DEVDIR/run.sh

if [ $# -eq 0 ]; then
  echo To set up to run with this build:
  echo
  echo "> source $RUNSCRIPT"
  echo "> COMMAND"
  echo
  echo or
  echo
  echo "> lbne run COMMAND"
else
  source $RUNSCRIPT
  echo $LBNE_LINE
  echo Running command: $*
  echo $LBNE_LINE
  $*
  echo $LBNE_LINE
fi
