#!/bin/bash

# lbnecheckout
# Check out the development packages.

# Perform setup if needed.
if test -z $LBNE_IS_SETUP; then
  source ./lbnesetup.sh
  if test -z $LBNE_IS_SETUP; then
    echo LBNE setup failed.
    exit 1
  fi
fi

PKGFILE=$LBNE_DEVDIR/packages.txt
if ! test -r $PKGFILE; then
  echo Package file not found: $PKGFILE
  exit 1
fi

# Create working area if needed.
HAVE_WORKDIR=`ls -d workdir 2>/dev/null`
echo $LBNE_LINE
if [ -z "$HAVE_WORKDIR" ]; then
  echo Creating new workdir
  mkdir workdir
else
  echo Using existing workdir
fi

cd $LBNE_DEVDIR/workdir

echo $LBNE_LINE
echo Setting up larsoft
setup larsoft $LBNE_LARVERSION -q $LBNE_QUAL

if [ -z "$HAVE_WORKDIR" ]; then
  echo $LBNE_LINE
  echo Creating mrb area
  mrb newDev 
  echo MRB_BUILDIR = $MRB_BUILDDIR
fi

pwd
source localProducts_$LBNE_LARPROD/setup

cd srcs
# Loop over local packages and check out if not already present.
echo $LBNE_LINE
echo Checking out packages
LOCALPRODS=`cat $PKGFILE`
for PKG in $LOCALPRODS; do
  echo $LBNE_LINE
  if test -r $PKG; then
    echo Package $PKG is already checked out
  else
    echo Checking out $PKG
    if [ $PKG = LArViewer ]; then
      git clone https://github.com/czczc/LArViewer.git
      cp -r LArViewer/LBNE35t/DataConverter lbnecode/lbne
    else
      mrb gitCheckout $PKG
      echo $LBNE_LINE
      echo Create local feature branch
      cd $PKG
      #tmp git flow feature start $GIT_BRANCH_NAME
      cd ..
    fi
  fi
done

exit 2

echo $LBNE_LINE
echo Building
cd $MRB_BUILDDIR
mrbsetenv
mrb i -j4

echo Set up to run
mrbslp
cd $THISDIR

echo
echo Generate an event: lar -n 10 -c prodsingle_lbne35t.fcl
echo Event display: lar -c evd_lbne35t.fcl single35t_gen.root
