#!/bin/sh

# lbnehelp
#
# David Adams
# July 2014
#
# Show avalable lbne commands.

echo '
  Usage: lbne COM [ARG]
  
  COM
  ---
  checkout - To check out the packages listed in packages.txt.
  build - To build all checked-out packages.
  clean - To remove files added by the build system (mrb z)
  restart - To remove build and checked-out packages
  show - Shows configuration information.
  showenv - Shows configuration environment.
  runscript - Install the runs cript used in run and shell
  run - Run the command ARG.
  shell - Start a shell to run commands.
  upslist - List available versions of UPS packge ARG [larsoft]
  help - This message.
  readme - Display the documentation from the package readme.

  The build configuration is specified in config.sh.
  The list of checked-out packages is in packages.txt.
'

