#!/bin/bash

# lbnebuild
#
# David Adams
# July 2014
#
# Build the checked-out code.

# LBNE setup.
source $LBNE_INSDIR/lbneinit.sh


echo $LBNE_LINE
cd $LBNE_DEVDIR/workdir
echo Setting up $LBNE_PROJECT
setup $LBNE_PROJECT $LBNE_PROJECTVERSION -q $LBNE_QUAL

echo $LBNE_LINE
cd $LBNE_DEVDIR/workdir
echo Setting up local products
source localProducts_$LBNE_PRODUCT/setup

echo $LBNE_LINE
cd $MRB_BUILDDIR
echo Building in `pwd`
if [ -n "$LBNE_VERBOSE" ]; then echo Running mrbsetenv; fi
mrbsetenv

echo $LBNE_LINE
COM="mrb i -j4"
if [ -n "$LBNE_VERBOSE" ]; then echo Running $COM; fi
$COM 
echo "$COM" >> $LBNE_HISTORY

echo $LBNE_LINE
echo Set up to run
if [ -n "$LBNE_VERBOSE" ]; then echo Running mrbslp; fi
mrbslp
cd $THISDIR

if [ -n "$LBNE_VERBOSE" ]; then echo exiting lbnebuild; fi
