#!/bin/sh

# lbnehelp
#
# David Adams
# July 2014
#
# Show avalable lbne commands.

echo '
  Usage: lbne COM [RUNCOM]
  
  COM
  ---
  checkout - To check out the packages listed in packages.txt.
  build - To build all checked-out packages.
  clean - To remove build and checked-out packages
  show - Shows configuration information.
  showenv - Shows configuration environment.
  run - Run the command RUNCOM.
  help - This message.

  The build configuration is specified in config.sh.
  The list of checked-out packages is in packages.txt.
'

