#!/bin/bash

# lbnerunscript
# Create setup file for running.

RUNSCRIPT=$LBNE_DEVDIR/run.sh
if [ ! -r $RUNSCRIPT ]; then
  echo "source $LBNE_INSDIR/lbneinit.sh" >>$RUNSCRIPT
  for SETUP in $LBNE_DEVDIR/workdir/localProducts*/setup; do
    echo source $SETUP >>$RUNSCRIPT
  done
  echo mrbslp >>$RUNSCRIPT
  echo "PS1=\"lbne-dev> \"" >>$RUNSCRIPT
fi
