#!/bin/bash

# lbnecheckout
#
# David Adams
# July 2014
#
# Check out the development packages.

# LBNE setup.
source $LBNE_INSDIR/lbneinit.sh

PKGFILE=$LBNE_DEVDIR/packages.txt
if ! test -r $PKGFILE; then
  echo Package file not found: $PKGFILE
  exit 1
fi

# Create working area if needed.
HAVE_WORKDIR=`ls -d workdir 2>/dev/null`
echo $LBNE_LINE
if [ -z "$HAVE_WORKDIR" ]; then
  echo Creating new workdir
  mkdir workdir
else
  echo Using existing workdir
fi

cd $LBNE_DEVDIR/workdir

echo $LBNE_LINE
echo Setting up $LBNE_PROJECT
setup $LBNE_PROJECT $LBNE_PROJECTVERSION -q $LBNE_QUAL

if [ -z "$HAVE_WORKDIR" ]; then
  echo $LBNE_LINE
  echo Creating mrb area
  mrb newDev 
  echo MRB_BUILDIR = $MRB_BUILDDIR
fi

pwd
source localProducts_$LBNE_PRODUCT/setup

cd srcs
# Loop over local packages and check out if not already present.
echo $LBNE_LINE
echo Checking out packages
LOCALPRODS=`cat $PKGFILE | sed 's/#.*//g'`
for PKG in $LOCALPRODS; do
  PKGPREFIX=`echo $PKG | awk -F/ '{print $1}'`
  PKGBASE=`basename $PKG`
  echo $LBNE_LINE
  if test -r $PKGBASE; then
    echo Package $PKG is already checked out
  else
    echo Checking out $PKG
    if [ $PKG = LArViewer ]; then
      git clone https://github.com/czczc/LArViewer.git
      cp -r LArViewer/LBNE35t/DataConverter lbnecode/lbne
    else
      mrb gitCheckout $PKG
      echo $LBNE_LINE
      echo Create local feature branch
      cd $PKGBASE
      #tmp git flow feature start $GIT_BRANCH_NAME
      cd ..
    fi
  fi
done

echo $LBNE_LINE
exit 5

echo $LBNE_LINE
echo Set up to run
mrbslp
cd $THISDIR

echo
echo Generate an event: lar -n 10 -c prodsingle_lbne35t.fcl
echo Event display: lar -c evd_lbne35t.fcl single35t_gen.root
echo $LBNE_LINE
