#!/bin/sh
#
# lbneclean
#
# David Adams
# July 2014

if test -z "$LBNE_DEVDIR"; then
  echo Development directory not found.
  exit 1
fi

echo Cleaning...
rm -rf $LBNE_DEVDIR/workdir
rm -rf $LBNE_DEVDIR/run.sh
