#!/bin/bash

# lbnebuild
# Build checked-out code.

# LBNE setup.
source $LBNE_INSDIR/lbnesetup.sh

cd $LBNE_DEVDIR/workdir
echo $LBNE_LINE
echo Setting up for local products
#source /grid/fermiapp/products/larsoft/setup

echo $LBNE_LINE
echo Setting up larsoft
setup larsoft $LBNE_LARVERSION -q $LBNE_QUAL

source localProducts_$LBNE_LARPROD/setup

echo $LBNE_LINE
echo Building
cd $MRB_BUILDDIR
mrbsetenv
mrb i -j4

echo Set up to run
mrbslp
cd $THISDIR
