#!/bin/sh

SUBCOM=$1
shift
ARGS="$*"

if [ -z "$SUBCOM" -o "$SUBCOM" = "-h" ]; then
  echo Usage: lbne COM
  echo "  COM = checkout, build, show, ..."
  echo "  For details, see \"lbne help\""
  exit 0
fi

COM=$LBNE_INSDIR/lbne$SUBCOM
if ! test -x $COM; then
  echo Command not found: $SUBCOM
  exit 1
fi

$COM $ARGS
  
